[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "deer-agent-framework"
version = "0.1a3"
description = "DEER - Deterministic Executable Engine for Runtime-agents"
authors = [{ name = "Yeison" }]
license = { text = "BSD-2-Clause" }
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.0",
    "rich",
    "prompt_toolkit",
]

[project.optional-dependencies]
debug = [
    "matplotlib>=3.10.9",
    "pandas>=3.0.3",
    "pytest>=9.0.3",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["deer*"]

[project.scripts]
deer = "deer.main:main"